#ifndef BOLIXO_H
#define BOLIXO_H

enum ENTRY_TYPE{
	ENTRY_NONE,
	ENTRY_DELETED,
	ENTRY_DIR,
	ENTRY_FILE,
	ENTRY_MSG
};

inline bool bolixo_isfile (ENTRY_TYPE type)
{
	return type == ENTRY_FILE || type == ENTRY_MSG;
}
inline bool bolixo_isdir (ENTRY_TYPE type)
{
	return type == ENTRY_DIR;
}
inline bool bolixo_isdeleted(ENTRY_TYPE type)
{
	return type == ENTRY_DELETED;
}

enum FILE_TYPE {
	FILE_UNKNOWN,
	FILE_TEXT,
	FILE_SOUND,
	FILE_IMAGE,
	FILE_VIDEO,
};

enum ERR_CODE{
	ERR_CODE_NONE,
	ERR_CODE_WARNING,
	ERR_CODE_FAIL,
	ERR_CODE_INVALID,
	ERR_CODE_NOPASSPHRASE,
	ERR_CODE_IVLDACCOUNT,
	ERR_CODE_CANTSIGN,
	ERR_CODE_NOSIGFOUND,
	ERR_CODE_VERIFYFAILED,
	ERR_CODE_CANTVERIFY
};

#endif

