extern const char **_dictionary_bolixo;
#ifndef DICTIONARY_REQUEST
	#define DICTIONARY_REQUEST \
	const char **_dictionary_bolixo;\
	TRANSLATE_SYSTEM_REQ _dictionary_req_bolixo("bolixo",_dictionary_bolixo,160,3);\
	void dummy_dict_bolixo(){}
#endif
#ifndef MSG_U
	#define MSG_U(id,m)	_dictionary_bolixo[id]
	#define MSG_B(id,m,n)	_dictionary_bolixo[id]
	#define MSG_R(id)	_dictionary_bolixo[id]
	#define P_MSG_U(id,m)	new_trans_notload(_dictionary_bolixo,id)
	#define P_MSG_B(id,m,n)	new_trans_notload(_dictionary_bolixo,id)
	#define P_MSG_R(id)	new_trans_notload(_dictionary_bolixo,id)
#endif
#define I_DBNAME	0
#define I_LISTEN	1
#define I_DBSERV	2
#define I_DUMPALL	3
#define I_BOLIXOD	4
#define I_DELETEDOC	5
#define E_NODUCUMENT	6
#define Q_DELETEALLDOC	7
#define I_DELETEDOCS	8
#define I_DELETEALLDOC	9
#define I_DELUSERS	10
#define Q_DELETEALLUSERS	11
#define I_DELETEALLUSERS	12
#define E_NOUSER	13
#define E_OWNDOC	14
#define I_DELUSER	15
#define T_BOLIXO	16
#define E_NOCON	17
#define M_FILE	18
#define M_OPEN	19
#define M_OPTIONS	20
#define M_QUIT	21
#define M_NODES	22
#define M_CLEARNODE	23
#define F_SERVER	24
#define F_PORT	25
#define F_DOCUMENT	26
#define T_SELDOC	27
#define M_LISTNODE	28
#define M_LISTREL	29
#define M_SHOWMAP	30
#define I_ADDUSER	31
#define I_SETPASSWD	32
#define E_UNKNOWNDOC	33
#define E_NONEWUSER	34
#define I_NAME	35
#define I_PASSWORD	36
#define I_DOCUMENT	37
#define E_NOPASSWD	38
#define E_PASSNOCHANGE	39
#define E_UNKNOWNUSER	40
#define F_USER	41
#define F_PASS	42
#define T_NODES	43
#define H_NODES	44
#define I_DEFDOC	45
#define I_DEFUSER	46
#define T_RELS	47
#define H_RELS	48
#define I_IMPORT	49
#define I_LISTDOC	50
#define M_CLOSE	51
#define B_SAVE	52
#define I_SAVE	53
#define B_CLOSE	54
#define I_CLOSE	55
#define M_SAVE	56
#define B_NEWNODE	57
#define I_NEWNODE	58
#define B_NEWREL	59
#define I_NEWREL	60
#define F_NODE1	61
#define F_RELATION	62
#define F_NODE2	63
#define F_NAME	64
#define F_IMAGE	65
#define E_NODEEXIST	66
#define I_PASSWD	67
#define I_CONNECTED	68
#define E_RELEXIST	69
#define I_DOCCHANGED	70
#define I_DUMPDOC	71
#define E_NODOC	72
#define I_MNGUSER	73
#define I_DOCMNG	74
#define I_NETSECUR	75
#define I_DBOPT	76
#define I_SUBOPT	77
#define I_BOLIXO	78
#define M_DOCUMENT	79
#define M_NEWNODE	80
#define M_NEWREL	81
#define M_DELETE	82
#define B_DELETE	83
#define I_DELETE	84
#define M_CHAT	85
#define M_PROTOCOL	86
#define E_ISLINKED	87
#define F_DEFSERVER	88
#define F_DEFPORT	89
#define T_PREFS	90
#define M_PREFS	91
#define M_IDENT	92
#define T_MAP	93
#define I_NBNODES	94
#define I_NBRELS	95
#define M_3DMAP	96
#define B_3DMAP	97
#define I_3DMAP	98
#define M_ATTRIBS	99
#define B_ATTRIBS	100
#define I_ATTRIBS	101
#define M_ADDATTR	102
#define M_REVERT	103
#define M_SHOWTREE	104
#define T_TREENODES	105
#define I_ORPHAN	106
#define I_LEAF	107
#define I_ROOT	108
#define I_BRANCH	109
#define M_EDITNODE	110
#define M_UNLINK	111
#define M_LINK	112
#define I_LINKDONE	113
#define E_NOLINKDONE	114
#define F_ALTNAME	115
#define I_BOSHELL	116
#define I_PORT	117
#define I_SERVER	118
#define I_USER	119
#define E_SETNEEDARG	120
#define E_IVLDSETCMD	121
#define E_NOSERVER	122
#define E_NOPORT	123
#define E_NODOCUMENT	124
#define I_CONOK	125
#define E_ERRCON	126
#define E_NOUSERDEF	127
#define E_NOPASSWDDEF	128
#define E_CANTCONNECT	129
#define E_REJCON	130
#define I_NOPWDSET	131
#define I_CONNECTON	132
#define I_CONNECTOFF	133
#define E_NODIR	134
#define E_IVLDCOMMAND	135
#define E_LSFAILED	136
#define I_CONNECT	137
#define M_LISTORPHAN	138
#define T_OPHANS	139
#define I_ORPHANB	140
#define I_ROOTNODE	141
#define I_ROOTB	142
#define E_ERRPROTO	143
#define I_SRVMSG	144
#define I_CREATEDOC	145
#define E_NONAME	146
#define M_LINKROOT	147
#define I_SECTION	148
#define I_PART	149
#define B_ADDNODE	150
#define I_ADDNODE	151
#define B_PREVNODE	152
#define I_PREVNODE	153
#define B_NEXTNODE	154
#define I_NEXTNODE	155
#define E_NODENAME	156
#define M_RAISE	157
#define M_LOWER	158
#define M_PRINT	159
