extern const char **_dictionary_bolixo;
#ifndef DICTIONARY_REQUEST
	#define DICTIONARY_REQUEST \
	const char **_dictionary_bolixo;\
	TRANSLATE_SYSTEM_REQ _dictionary_req_bolixo("bolixo",_dictionary_bolixo,247,6);\
	void dummy_dict_bolixo(){}
#endif
#ifndef MSG_U
	#define MSG_U(id,m)	_dictionary_bolixo[id]
	#define MSG_B(id,m,n)	_dictionary_bolixo[id]
	#define MSG_R(id)	_dictionary_bolixo[id]
	#define P_MSG_U(id,m)	new_trans_notload(_dictionary_bolixo,id)
	#define P_MSG_B(id,m,n)	new_trans_notload(_dictionary_bolixo,id)
	#define P_MSG_R(id)	new_trans_notload(_dictionary_bolixo,id)
#endif
#define E_CONFMISSING	0
#define E_CANTMODIFY	1
#define I_BOFS	2
#define O_SELECT	3
#define O_REPEAT	4
#define M_MAIN	5
#define M_TALK	6
#define M_MAIL	7
#define M_PROJECTS	8
#define M_PROFILE	9
#define M_DOCUM	10
#define E_KEYWORD	11
#define I_BOFSCONF	12
#define E_NOUSER	13
#define E_IVLDCOMMAND	14
#define E_SAVECURFORM	15
#define E_RESTOREFORM	16
#define E_SAVEFORM	17
#define T_LOGIN	18
#define B_LOGIN	19
#define T_CREATEACC	20
#define H_PROJECTS	21
#define I_CREATENEWDOC	22
#define E_CREATEFOLDER	23
#define E_INTERNAL	24
#define I_NEW_FOLDER	25
#define I_UPLOADFILE	26
#define H_FOLDER	27
#define I_DOCNAME	28
#define B_SAVE	29
#define T_MAILS	30
#define H_MAILS	31
#define I_INBOX	32
#define T_TALKS	33
#define H_TALKS	34
#define B_SEND	35
#define E_CANTSEND	36
#define E_REACHMISS	37
#define E_CONFIRMFAILED	38
#define T_PROFILE	39
#define I_CREATELIST	40
#define H_INBOXES	41
#define T_ACCOUNT	42
#define T_INTERESTS	43
#define T_CONTACTS	44
#define T_PROJECTS	45
#define T_GROUPS	46
#define H_PROF_PROJECTS	47
#define I_LANG	48
#define I_ENGLISH	49
#define I_FRENCH	50
#define I_ENABLEPUB	51
#define I_PUBFOLDER	52
#define E_CANTSAVECONFIG	53
#define I_CONFIGUPDATED	54
#define I_CREATEGROUP	55
#define H_GROUPS	56
#define I_NEWCONTACT	57
#define H_CONTACTS	58
#define I_WAITING	59
#define I_ACCEPTED	60
#define I_REJECTED	61
#define I_SENDCONTACT	62
#define I_TOCONTACT	63
#define I_MESSAGE	64
#define E_CONTACTFAIL	65
#define I_CONTACTSENT	66
#define I_GROUP	67
#define I_DESCRIPTION	68
#define I_MEMBERS	69
#define E_CANTCREATEGROUP	70
#define E_CANTSETGROUPDESC	71
#define E_CANTSETMEMBER	72
#define E_CANTDELMEMBER	73
#define T_PROJECT	74
#define I_PRJ_PROJECT	75
#define I_PRJ_DESCRIPTION	76
#define I_PRJ_MEMBERS	77
#define I_PRJ_GROUP	78
#define H_TALK	79
#define E_CANTREADFILE	80
#define I_INHERIT	81
#define I_READONLY	82
#define I_READWRITE	83
#define E_HTTPLOGIN	84
#define E_IVLDPATH	85
#define E_UPDGROUP	86
#define I_ACCTCONFIRM	87
#define I_HAVEACCT	88
#define I_EMAIL	89
#define I_PASSWORD	90
#define I_PASSWDREQ	91
#define I_PROVIDEEMAIL	92
#define I_LOGINFAILED	93
#define I_NOACCOUNT	94
#define I_MOREDETAILS	95
#define I_NICKNAME	96
#define I_ENTERMAIL	97
#define I_ENTERPWD	98
#define I_CONFIRMPWD	99
#define B_ACCACCOUNT	100
#define E_NEEDNICKMAME	101
#define E_NEEDEMAIL	102
#define E_NEEDPWD	103
#define E_PWDMISMATCH	104
#define E_CREATACCT	105
#define I_ACCTCREATED	106
#define I_WELCOME	107
#define I_ANONYMOUS	108
#define I_LOGIN	109
#define I_CREATEACCT	110
#define I_LOGOUT	111
#define I_ABOUT	112
#define I_NEWDOCNAME	113
#define I_HOPESEEYOU	114
#define I_BOD_CONTROL	115
#define I_BOD_SOCK	116
#define E_UNKNOWNUSER	117
#define E_LOGIN	118
#define E_IVLDSESSION	119
#define E_NOPUBLICACC	120
#define E_NOTAFILE	121
#define E_USEREADBOB	122
#define E_NOTDIR	123
#define E_NOTALLOWEDLIST	124
#define E_NOLIST	125
#define E_NOGROUP	126
#define E_ACCESSDEN	127
#define E_ALREADY	128
#define E_IVLDNAME	129
#define E_NOTALLOWCREATE	130
#define E_NOMODIFY	131
#define E_NAMENOTDIR	132
#define I_BORM	133
#define E_CANTDELETE	134
#define E_READDIR	135
#define E_DOESNOTEXIST	136
#define E_NOPUBKEY	137
#define E_SIGNOMATCH	138
#define I_SIGOK	139
#define E_GROUPPROBLEMS	140
#define E_OFFSETLARGE	141
#define E_SEEKFAIL	142
#define O_TESTMODE	143
#define I_VIEWNEW	144
#define I_VIEWSEEN	145
#define I_VIEWCHANGED	146
#define I_TITLE	147
#define I_MANAGECONTACT	148
#define I_REQUESTFROM	149
#define I_ACCEPTREQ	150
#define I_REFUSEREQ	151
#define I_CONTACTDONE	152
#define I_FROMNOWON	153
#define I_MAKEMEMBER	154
#define I_HEMAKEMEMBER	155
#define E_USERNOTSET	156
#define E_ALREADYSET	157
#define E_IVLDUSER	158
#define E_INTUSER	159
#define I_BOFSMISC	160
#define I_MAINCOMMAND	161
#define I_CONTACTMGMT	162
#define I_INTERESTMGMT	163
#define I_VERIYSIGN	164
#define I_WRITECONFIG	165
#define I_HELLOCONTACT	166
#define E_CANTUPDDATEDIR	167
#define I_NEWDOC	168
#define I_FROM	169
#define I_DATE	170
#define I_PROJECT	171
#define I_HELP	172
#define I_TALKGROUP	173
#define I_TALKFROM	174
#define I_HELPPROJECTS	175
#define I_HELPGROUPS	176
#define I_HELPCONTACTS	177
#define I_HELPACCOUNT	178
#define E_MKDIR	179
#define E_DONEBYCONTACT	180
#define E_CONTACTDONE	181
#define E_CONTACTMANAGED	182
#define I_OR	183
#define I_NEW	184
#define I_MOD	185
#define I_BLK	186
#define E_NOTALLOWED	187
#define I_HELPINTERESTS	188
#define I_NEWINTEREST	189
#define I_ADDINTEREST	190
#define I_PEOPLES	191
#define E_INTERESTSET	192
#define E_INTERESTDUP	193
#define H_INTEREST	194
#define E_UNKNOWNOWNER	195
#define E_UNKNOWNGROUP	196
#define E_UNKOWNUSER	197
#define E_UNKNOWNPUBDIR	198
#define E_PUBDIRNOTDIR	199
#define O_ADDATTACH	200
#define O_LISTINBOXES	201
#define O_LISTALLINBOXES	202
#define O_SENDMSG	203
#define O_REPLYMSG	204
#define O_SENDSHORTMSG	205
#define O_SENDFILE	206
#define O_LISTSHORTMSGS	207
#define O_GROUPNAME	208
#define O_GROUPOWNER	209
#define O_MANAGER	210
#define O_TARGETINBOX	211
#define O_TARGETROLE	212
#define O_RECIPIENT	213
#define O_FILEMSG	214
#define O_MSGID	215
#define O_TITLE	216
#define O_BODY	217
#define O_BOFILEPATH	218
#define O_OWNER	219
#define T_CONTACT_REQS	220
#define I_HELPCONTACT_REQ	221
#define I_NONE	222
#define I_ROOTDIR	223
#define M_COPY	224
#define M_PASTE	225
#define M_DELETE	226
#define M_PREVIEWPUB	227
#define M_HELPPREVIEW	228
#define I_HELPPREVIEW	229
#define E_CANTDELETEENTRY	230
#define E_CANTDELETEDIR	231
#define E_CANTUNDELETEENTRY	232
#define M_UNDELETE	233
#define E_CANTUNDELETE	234
#define E_NOTAFILECANTDEL	235
#define E_NOTDIRUNDEL	236
#define E_NODELETED	237
#define M_RENAME	238
#define E_NOTHINGTOPASTE	239
#define E_CANTPASTEENTRY	240
#define F_OLDNAME	241
#define F_NEWNAME	242
#define E_RENAME	243
#define M_DOWNLOAD	244
#define E_ONLYFILE	245
#define E_ONLYFILEANDDIR	246
