#!/bin/sh
if [ "$1" = "" ] ; then
	echo eximrm mailid
	exit 1
fi
DATA=/var/lib/lxc/exim/rootfs/tmp/eximrm.data
echo /usr/sbin/exim >$DATA
echo "-Mrm" >>$DATA
echo "$1" >>$DATA
cp /usr/lib/eximexec /var/lib/lxc/exim/rootfs/usr/bin/eximexec
lxc-attach -n exim /usr/bin/eximexec
