#!/bin/sh
if [ "$1" = "" ] ; then
	echo eximrm mailid ...
	exit 1
fi
DATA=/var/lib/lxc/exim/rootfs/tmp/eximrm.data
cp /usr/lib/eximexec /var/lib/lxc/exim/rootfs/usr/bin/eximexec
for id in $*
do
	echo /usr/sbin/exim >$DATA
	echo "-Mrm" >>$DATA
	echo "$id" >>$DATA
	lxc-attach -n exim /usr/bin/eximexec
done
