#!/bin/sh
if [ "$1" = "--name" ] ; then
	bolixo-production users --silent <<-EOF
	select name from users where userid > 0 order by name;
	EOF
else
	bolixo-production users -t <<-EOF
	select userid,name,email,created,confirmed,lastaccess,nbfail from users where userid != -2 order by name;
	EOF
fi

