#!/bin/sh
NB=20
if [ "$1" != "" ] ; then
	NB=$1
fi
grep -v 'SMTP protocol error in "AUTH LOGIN"' /var/lib/lxc/exim/rootfs/var/log/exim/main.log | \
	grep -v "queue run:" | \
	grep -v "rejected HELO from" | \
	tail -$NB
echo ====== queue ======
lxc-attach -n exim mailq

