#!/bin/sh
CMD="tail -20"
if [ "$1" = "all" ] ;then
	CMD=cat
elif [ "$1" != "" ] ;then
	CMD="tail -$1"
fi
$CMD /var/lib/lxc/webssl/rootfs/etc/httpd/logs/ssl_access_log | while read line
do
	case $line in
	*GET\ /index.hc?webstep=12*)
		echo "Documentation" $line
		;;
	*GET\ /index.hc?webstep=11*)
		echo "Profile      " $line
		;;
	*GET\ /index.hc?webstep=10*)
		echo "Confirmuser  " $line
		;;
	*GET\ /index.hc?webstep=9*)
		echo "Talk         " $line
		;;
	*GET\ /index.hc?webstep=8*)
		echo "Mails        " $line
		;;
	*GET\ /index.hc?webstep=7*)
		echo "Projects     " $line
		;;
	*GET\ /index.hc?webstep=6*)
		echo "Publicfile   " $line
		;;
	*GET\ /index.hc?webstep=5*)
		echo "Privatefile  " $line
		;;
	*GET\ /index.hc?webstep=4*)
		echo "Logout       " $line
		;;
	*GET\ /index.hc?webstep=3*)
		echo "Adduser      " $line
		;;
	*GET\ /index.hc?webstep=2*)
		echo "Login        " $line
		;;
	*GET\ /index.hc?webstep=1*)
		echo "Main page    " $line
		;;
	*GET\ /\ *)
		echo "Main page    " $line
		;;
	*POST\ /index.hc\ *)
		echo "POST         " $line
		;;
	*\ 404\ *)
		echo "BAD          " $line
		;;
	*)
		echo "Other        " $line
		;;
	esac
done

