#!/bin/sh
IP=`ifconfig eth0 | grep inet | (read a b c; echo $b)`
echo ====== monitor ========
bolixo-production monitor | grep services
if [ ! -f /etc/bolixo/running ] ; then
	echo /etc/bolixo/running missing, cron disabled
fi
echo ====== protocheck =====
/var/lib/lxc/protocheck/status.sh| grep rejected: | grep -v "rejected: 0"
echo ====== syslog =========
bolixo-production syslog-tail
echo ====== pendings =======
pendingusers
echo ====== webssl =========
logssl
echo ====== exim ===========
logexim 10
echo ====== stats ==========
NBHIT=`fgrep -v bo-webtest /var/lib/lxc/web/rootfs/tmp/agent.log | wc -l`
NBROB=`fgrep -v bo-webtest /var/lib/lxc/web/rootfs/tmp/agent.log | grep -c robot=1`
TODAY=`date +%d/%b/%Y`
echo    "Today      " `fgrep -v $IP /var/lib/lxc/webssl/rootfs/etc/httpd/logs/ssl_access_log | grep -c $TODAY`
echo    "robots     " $NBROB/$NBHIT
echo -n "nbusers     "
nbusers
blackhole-stats | grep " 443 "

